<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <DebugType>None</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UIAutomationClient" />
    <Reference Include="UIAutomationTypes" />
    <Reference Include="WindowsBase" />
    <PackageReference
      Include="Microsoft.NETFramework.ReferenceAssemblies"
      Version="1.0.3"
      PrivateAssets="All"
    />
  </ItemGroup>
</Project>
